const w1200Product = [
	{
		bgClass: "blue-bg",
		labelText: "CATEGORY | MARKETING",
		img: "./assets/card1.png",
		txtClass: "blue-txt",
		authorText: "Adam Sandler",
		productName: "Solutions for people like you like people",
		productText: "How can we help your technology and services business develop a revenue engine based",
	},
	{
		bgClass: "blue-bg",
		labelText: "CATEGORY",
		img: "./assets/card2.png",
		txtClass: "blue-txt",
		authorText: "Adam Sandler",
		productName: "Solutions for people like you like people",
		productText: "How can we help your technology and services business develop a revenue engine based",
	},
	{
		bgClass: "darkBlue-bg",
		labelText: "CATEGORY | DEVELOPMENT",
		img: "./assets/card3.png",
		txtClass: "darkBlue-txt",
		authorText: "Adam Sandler",
		productName: "Solutions for people like",
		productText: "How can we help your technology and services business develop a revenue engine based",
	},
	{
		bgClass: "darkBlue-bg",
		labelText: "CATEGORY | MARKETING",
		img: "./assets/card4.png",
		txtClass: "darkBlue-txt",
		authorText: "Adam Sandler",
		productName: "Solutions for people like you like people",
		productText: "How can we help your technology and services business develop a revenue engine based",
	},
	{
		bgClass: "blue-bg",
		labelText: "CATEGORY | MARKETING",
		img: "./assets/card5.png",
		txtClass: "blue-txt",
		authorText: "Adam Sandler",
		productName: "Solutions for people",
		productText: "How can we help your technology and services business develop a revenue engine based",
	},
	{
		bgClass: "darkBlue-bg",
		labelText: "CATEGORY",
		img: "./assets/card1.png",
		txtClass: "darkBlue-txt",
		authorText: "Adam Sandler",
		productName: "Solutions for people like you like people",
		productText: "How can we help your technology and services business develop a revenue engine based",
	},
];

const w1199Product = [
	{
		bgClass: "blue-bg",
		labelText: "CATEGORY | MARKETING",
		img: "./assets/card1.png",
		txtClass: "blue-txt",
		authorText: "Adam Sandler",
		productName: "Solutions for people like you like people",
		productText: "How can we help your technology and services business develop a revenue engine based...",
	},
	{
		bgClass: "darkBlue-bg",
		labelText: "CATEGORY | MARKETING",
		img: "./assets/card3.png",
		txtClass: "darkBlue-txt",
		authorText: "Adam Sandler",
		productName: "Solutions for people like you like people",
		productText: "How can we help your technology and services business develop a revenue engine based...",
	},
	{
		bgClass: "darkBlue-bg",
		labelText: "CATEGORY | MARKETING",
		img: "./assets/card4.png",
		txtClass: "darkBlue-txt",
		authorText: "Adam Sandler",
		productName: "Solutions for people like you like people",
		productText: "How can we help your technology and services business develop a revenue engine based...",
	},
	{
		bgClass: "blue-bg",
		labelText: "CATEGORY | MARKETING",
		img: "./assets/card6.png",
		txtClass: "blue-txt",
		authorText: "Adam Sandler",
		productName: "Solutions for people like you like people",
		productText: "How can we help your technology and services business develop a revenue engine based...",
	},
];

const w767Product = [
	{
		bgClass: "blue-bg",
		labelText: "CATEGORY | MARKETING",
		img: "./assets/card1.png",
		txtClass: "blue-txt",
		authorText: "Adam Sandler",
		productName: "Solutions for people like you like people solutions for people like you",
		productText: "How can we help your technology and services business develop...",
	},
	{
		bgClass: "darkBlue-bg",
		labelText: "CATEGORY | MARKETING",
		img: "./assets/card3.png",
		txtClass: "darkBlue-txt",
		authorText: "Adam Sandler",
		productName: "Solutions for people like you like people solutions for people like you",
		productText: "How can we help your technology and services business develop...",
	},
	{
		bgClass: "darkBlue-bg",
		labelText: "CATEGORY | MARKETING",
		img: "./assets/card4.png",
		txtClass: "darkBlue-txt",
		authorText: "Adam Sandler",
		productName: "Solutions for people like you like people solutions for people like you",
		productText: "How can we help your technology and services business develop...",
	},
	{
		bgClass: "blue-bg",
		labelText: "CATEGORY | MARKETING",
		img: "./assets/card6.png",
		txtClass: "blue-txt",
		authorText: "Adam Sandler",
		productName: "Solutions for people like you like people solutions for people like you",
		productText: "How can we help your technology and services business develop...",
	},
];

const w575Product = [
	{
		bgClass: "blue-bg",
		labelText: "CATEGORY | MARKETING",
		img: "./assets/card1.png",
		txtClass: "blue-txt",
		authorText: "Adam Sandler",
		productName: "Solutions for people like you like people solutions for people like you",
		productText: "How can we help your technology and services business develop...",
	},
	{
		bgClass: "darkBlue-bg",
		labelText: "CATEGORY | MARKETING",
		img: "./assets/card3.png",
		txtClass: "darkBlue-txt",
		authorText: "Adam Sandler",
		productName: "Solutions for people like you like people solutions for people like you",
		productText: "How can we help your technology and services business develop...",
	},
];

const w1200Slider = [
	{
		bgClass: "blue-bg",
		labelText: "CATEGORY | MARKETING",
		img: "./assets/card1.png",
		txtClass: "blue-txt",
		authorText: "Adam Sandler",
		productName: "Solutions for people like you like people",
		productText: "How can we help your technology and services business develop a revenue engine based",
	},
	{
		bgClass: "blue-bg",
		labelText: "CATEGORY",
		img: "./assets/card2.png",
		txtClass: "blue-txt",
		authorText: "Adam Sandler",
		productName: "Solutions for people like you like people",
		productText: "How can we help your technology and services business develop a revenue engine based",
	},
	{
		bgClass: "darkBlue-bg",
		labelText: "CATEGORY | DEVELOPMENT",
		img: "./assets/card3.png",
		txtClass: "darkBlue-txt",
		authorText: "Adam Sandler",
		productName: "Solutions for people like",
		productText: "How can we help your technology and services business develop a revenue engine based",
	},
	{
		bgClass: "darkBlue-bg",
		labelText: "CATEGORY | MARKETING",
		img: "./assets/card4.png",
		txtClass: "darkBlue-txt",
		authorText: "Adam Sandler",
		productName: "Solutions for people like you like people",
		productText: "How can we help your technology and services business develop a revenue engine based",
	},
	{
		bgClass: "blue-bg",
		labelText: "CATEGORY | MARKETING",
		img: "./assets/card5.png",
		txtClass: "blue-txt",
		authorText: "Adam Sandler",
		productName: "Solutions for people",
		productText: "How can we help your technology and services business develop a revenue engine based",
	},
	{
		bgClass: "darkBlue-bg",
		labelText: "CATEGORY",
		img: "./assets/card1.png",
		txtClass: "darkBlue-txt",
		authorText: "Adam Sandler",
		productName: "Solutions for people like you like people",
		productText: "How can we help your technology and services business develop a revenue engine based",
	},
];
